package com.example.devopsproj.utils;

import com.example.devopsproj.commons.enumerations.TokenType;
import com.example.devopsproj.model.Token;
import com.example.devopsproj.model.User;
import com.example.devopsproj.repository.TokenRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * The `JwtUtils` class provides utility methods for handling JWT tokens.
 * This is a util for decoding the jwt token generated by the frontend using signup with Google
 *
 * @version 2.0
 */

//
@Component
@RequiredArgsConstructor
public class JwtUtils {

    private final TokenRepository tokenRepository;

    public  void saveUserToken(User user, String jwtToken) {
        var token = Token.builder()
                .user(user)
                .tokenId(jwtToken)
                .tokenType(TokenType.BEARER)
                .expired(false)
                .revoked(false)
                .build();
        tokenRepository.save(token);
    }

}
