package com.example.DevOpsProj.utils;

import com.auth0.jwt.JWT;
import com.auth0.jwt.interfaces.DecodedJWT;
import org.springframework.stereotype.Component;

//util for decoding the jwt token generated by the frontend using signup with Google
@Component
public class JwtUtils {
    //get the email from the token
    public static String getEmailFromJwt(String jwt){
        DecodedJWT decodedJWT = JWT.decode(jwt);
        return decodedJWT.getClaim("email").asString();
    }

}
